<?php
declare(strict_types=1);
$c=json_decode(file_get_contents(__DIR__.'/data/config.json'),true,512,JSON_THROW_ON_ERROR);
$d=json_decode(file_get_contents(__DIR__.'/data/content.json'),true,512,JSON_THROW_ON_ERROR);
$ls=$c['site']['locales'];$def=$c['site']['default_locale'];$raw=trim(parse_url($_SERVER['REQUEST_URI']??'/',PHP_URL_PATH)??'/','/');$base=rtrim($c['site']['base_path']??'','/');$base=($base==='/'?'':$base);$path=$base&&($raw===trim($base,'/')||substr($raw,0,strlen(trim($base,'/'))+1)===trim($base,'/').'/')?trim(substr($raw,strlen(trim($base,'/'))),'/'):$raw;
$parts=$path?explode('/',$path):[];$locale=in_array($parts[0]??'', $ls,true)?array_shift($parts):$def;$root=$base?'/'.$base:'';
function tr($v,$l,$d){if(!is_array($v))return $v;if(array_key_exists($l,$v))return $v[$l];if(array_key_exists($d,$v))return $v[$d];foreach($v as $k=>$x)$v[$k]=tr($x,$l,$d);return $v;}
function e($v){return htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
$page=$parts[0]??'home';$content=$d[$page]??null;if(!$content){http_response_code(404);$page='home';$content=$d['home'];}$content=tr($content,$locale,$def);$common=tr($d['common']??[],$locale,$def);$switch=$locale==='en'?'tr':'en';
?><!doctype html><html lang="<?=e($locale)?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($c['theme']['title'])?></title><meta name="description" content="<?=e($c['theme']['description'])?>"><style>
*{box-sizing:border-box;margin:0;padding:0;line-height:1em}html{-webkit-text-size-adjust:100%}@media(max-width:639px){html{font-size:3.125vw}}@media(min-width:640px) and (max-width:1279px){html{font-size:1.5625vw}}@media(min-width:1280px){html{font-size:.78125vw}}body{background:#101413;color:#f5f3eb;font-family:system-ui,sans-serif}.site{width:128rem;min-height:100vh;margin:auto;padding:3rem 7rem;background:linear-gradient(135deg,#18231f,#101413)}a{color:inherit;text-decoration:none}.nav{display:flex;justify-content:space-between;align-items:center;padding-bottom:3rem;border-bottom:1px solid #40504a}.brand{font-size:2.4rem;font-weight:800}.links{display:flex;gap:3rem;color:#b8c4bd;font-size:1.4rem}.hero{max-width:85rem;padding:15rem 0 12rem}.eyebrow{color:#d4ef72;font-size:1.3rem;letter-spacing:.12rem;text-transform:uppercase;margin-bottom:3rem}.hero h1{font-size:8rem;line-height:.98;max-width:80rem;margin-bottom:3rem}.hero p{color:#b8c4bd;font-size:2rem;line-height:1.5;max-width:65rem}.button{display:inline-block;background:#d4ef72;color:#101413;padding:1.8rem 2.4rem;margin-top:4rem;font-size:1.5rem;font-weight:700}.section{display:grid;grid-template-columns:32rem 1fr;gap:8rem;padding:8rem 0;border-top:1px solid #40504a}.section h2{font-size:4rem;line-height:1}.section p{color:#b8c4bd;font-size:2rem;line-height:1.5;max-width:65rem}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:2rem;margin-top:4rem}.card{border:1px solid #40504a;padding:3rem;min-height:18rem}.card h3{font-size:2rem;margin-bottom:2rem}.card p{font-size:1.5rem;line-height:1.5;color:#b8c4bd}.footer{padding-top:5rem;color:#78877f;font-size:1.3rem}@media(max-width:1279px){.site{width:64rem;padding:3rem}.hero{padding:10rem 0}.hero h1{font-size:6rem}.cards{grid-template-columns:1fr}.section{grid-template-columns:1fr;gap:3rem}}@media(max-width:639px){.site{width:32rem;padding:2rem}.links{gap:1rem;font-size:1.2rem}.hero{padding:8rem 0}.hero h1{font-size:4.5rem}.hero p{font-size:1.7rem}.section{padding:5rem 0}.section h2{font-size:3rem}}
</style></head><body><main class="site"><nav class="nav"><a class="brand" href="<?=e($root)?>/">genes</a><div class="links"><a href="<?=e($root)?>/<?=e($locale)?>/"><?=e($common['nav']['home'])?></a><a href="https://github.com/devrimvardar/genes"><?=e($common['nav']['github'])?></a><a href="<?=e($root)?>/<?=e($switch)?>/"><?=e(strtoupper($switch))?></a></div></nav><section class="hero"><div class="eyebrow"><?=e($content['eyebrow'])?></div><h1><?=e($content['title'])?></h1><p><?=e($content['text'])?></p><a class="button" href="https://raw.githubusercontent.com/devrimvardar/genes/main/genes.md"><?=e($content['button'])?></a></section><section class="section"><h2><?=e($content['section_title'])?></h2><div><p><?=e($content['section_text'])?></p><div class="cards"><?php foreach($content['cards'] as $card):?><article class="card"><h3><?=e($card['title'])?></h3><p><?=e($card['text'])?></p></article><?php endforeach;?></div></div></section><footer class="footer"><?=e($common['footer'])?></footer></main></body></html>
