-- Example content. Runs once when data/content.sqlite is created.

INSERT INTO items (hash, type, status, slug, title, summary, text, published_at, created_at, updated_at) VALUES
    ('itm_seed000001', 'news', 'published', 'school-renovation-results',
    '{"en": "Kallio school: 41% less heating energy after one year", "tr": "Kallio okulu: bir yılda %41 daha az ısıtma enerjisi", "fi": "Kallion koulu: 41 % vähemmän lämmitysenergiaa vuodessa"}',
    '{"en": "Measured results from the first full heating season after the energy renovation.", "tr": "Enerji yenilemesinden sonraki ilk tam ısıtma sezonunun ölçülmüş sonuçları.", "fi": "Mitatut tulokset energiakorjauksen jälkeiseltä ensimmäiseltä täydeltä lämmityskaudelta."}',
    '{"en": "One year after handover, the renovated Kallio school used 41% less heating energy than in the three years before the work.\n\nThe largest savings came from ventilation heat recovery and the new windows. Indoor temperatures stayed stable through the winter, and the measured air tightness was better than the design target.\n\nWe publish the full measurement report for the building owner and other schools planning similar work.", "tr": "Teslimden bir yıl sonra yenilenen Kallio okulu, çalışmalardan önceki üç yıla göre %41 daha az ısıtma enerjisi kullandı.\n\nEn büyük tasarruf, ısı geri kazanımlı havalandırmadan ve yeni pencerelerden geldi. İç sıcaklıklar kış boyunca sabit kaldı ve ölçülen hava sızdırmazlığı tasarım hedefinden daha iyi çıktı.\n\nTam ölçüm raporunu bina sahibi ve benzer çalışma planlayan diğer okullar için yayımlıyoruz.", "fi": "Vuosi luovutuksen jälkeen korjattu Kallion koulu käytti 41 % vähemmän lämmitysenergiaa kuin töitä edeltävinä kolmena vuotena.\n\nSuurimmat säästöt tulivat ilmanvaihdon lämmöntalteenotosta ja uusista ikkunoista. Sisälämpötilat pysyivät tasaisina koko talven, ja mitattu ilmatiiviys oli suunnittelutavoitetta parempi.\n\nJulkaisemme koko mittausraportin rakennuksen omistajalle ja muille vastaavia töitä suunnitteleville kouluille."}',
    '2026-09-18T08:00:00Z', '2026-09-18T08:00:00Z', '2026-09-18T08:00:00Z');

INSERT INTO items (hash, type, status, slug, title, summary, text, published_at, created_at, updated_at) VALUES
    ('itm_seed000002', 'news', 'published', 'istanbul-timber-housing',
    '{"en": "Six-storey timber housing in Istanbul gets its permit", "tr": "İstanbul''da altı katlı ahşap konut ruhsatını aldı", "fi": "Kuusikerroksinen puukerrostalo Istanbuliin sai luvan"}',
    '{"en": "One of the first multi-storey CLT residential buildings in Türkiye moves to construction.", "tr": "Türkiye''nin ilk çok katlı CLT konut binalarından biri inşaat aşamasına geçiyor.", "fi": "Yksi Turkin ensimmäisistä monikerroksisista CLT-asuinrakennuksista etenee rakentamiseen."}',
    '{"en": "The building permit for a six-storey residential building with a cross-laminated timber frame was approved in Kadıköy.\n\nArkka''s Istanbul studio designed the structure, the connections, and the fire safety concept together with the architect and the local fire authority.\n\nConstruction starts in the autumn. The timber elements are made in Finland and shipped in numbered packages.", "tr": "Kadıköy''de çapraz lamine ahşap taşıyıcılı altı katlı bir konut binasının yapı ruhsatı onaylandı.\n\nArkka İstanbul stüdyosu, taşıyıcı sistemi, bağlantıları ve yangın güvenliği konseptini mimar ve yerel itfaiye ile birlikte tasarladı.\n\nİnşaat sonbaharda başlıyor. Ahşap elemanlar Finlandiya''da üretilip numaralı paketler halinde gönderiliyor.", "fi": "Kadıköyhyn suunnitellun kuusikerroksisen, CLT-runkoisen asuinrakennuksen rakennuslupa hyväksyttiin.\n\nArkan Istanbulin toimisto suunnitteli rungon, liitokset ja paloturvallisuuskonseptin yhdessä arkkitehdin ja paikallisen palolaitoksen kanssa.\n\nRakentaminen alkaa syksyllä. Puuelementit valmistetaan Suomessa ja toimitetaan numeroituina paketteina."}',
    '2026-06-03T08:00:00Z', '2026-06-03T08:00:00Z', '2026-06-03T08:00:00Z');

INSERT INTO items (hash, type, status, slug, title, summary, text, published_at, created_at, updated_at) VALUES
    ('itm_seed000003', 'news', 'published', 'moisture-survey-guide',
    '{"en": "A free guide to moisture surveys for housing companies", "tr": "Konut şirketleri için ücretsiz nem tespiti rehberi", "fi": "Maksuton kosteuskartoitusopas asunto-osakeyhtiöille"}',
    '{"en": "Eight pages on when to order a moisture survey and how to read the report.", "tr": "Nem tespitinin ne zaman yaptırılacağı ve raporun nasıl okunacağı üzerine sekiz sayfa.", "fi": "Kahdeksan sivua siitä, milloin kosteuskartoitus kannattaa tilata ja miten raporttia luetaan."}',
    '{"en": "Many boards order a moisture survey only after damage is visible. Our new guide explains the early signs and what a good survey includes.\n\nIt also shows how to read the priority list in a survey report and how to plan the repairs over several years.", "tr": "Birçok yönetim, nem tespitini ancak hasar görünür hale geldiğinde yaptırıyor. Yeni rehberimiz erken belirtileri ve iyi bir tespitin neleri içermesi gerektiğini açıklıyor.\n\nAyrıca bir rapordaki öncelik listesinin nasıl okunacağını ve onarımların birkaç yıla nasıl planlanacağını gösteriyor.", "fi": "Moni hallitus tilaa kosteuskartoituksen vasta, kun vaurio näkyy. Uusi oppaamme kertoo varhaisista merkeistä ja siitä, mitä hyvään kartoitukseen kuuluu.\n\nSe näyttää myös, miten raportin kiireellisyyslistaa luetaan ja miten korjaukset suunnitellaan usealle vuodelle."}',
    '2026-03-12T08:00:00Z', '2026-03-12T08:00:00Z', '2026-03-12T08:00:00Z');

INSERT INTO items (hash, type, status, slug, title, summary, text, published_at, created_at, updated_at) VALUES
    ('itm_seed000004', 'news', 'published', 'new-office-helsinki',
    '{"en": "Arkka moves to a renovated timber building in Helsinki", "tr": "Arkka, Helsinki''de yenilenmiş bir ahşap binaya taşındı", "fi": "Arkka muutti korjattuun puurakennukseen Helsingissä"}',
    '{"en": "Our Helsinki team now works in a 1920s building that we renovated ourselves.", "tr": "Helsinki ekibimiz artık kendi yenilediğimiz 1920''lerden kalma bir binada çalışıyor.", "fi": "Helsingin tiimimme työskentelee nyt 1920-luvun rakennuksessa, jonka korjasimme itse."}',
    '{"en": "After two years of planning and eight months of work, the Helsinki studio moved into a renovated 1920s timber building.\n\nThe building is now our test site: sensors log temperature, humidity, and energy use, and the data is open to our clients.", "tr": "İki yıllık planlama ve sekiz aylık çalışmanın ardından Helsinki stüdyosu, yenilenmiş 1920''lerden kalma bir ahşap binaya taşındı.\n\nBina artık test alanımız: sensörler sıcaklık, nem ve enerji kullanımını kaydediyor ve veriler müşterilerimize açık.", "fi": "Kahden vuoden suunnittelun ja kahdeksan kuukauden työn jälkeen Helsingin toimisto muutti korjattuun 1920-luvun puurakennukseen.\n\nRakennus on nyt testikohteemme: anturit tallentavat lämpötilaa, kosteutta ja energiankulutusta, ja tiedot ovat asiakkaidemme saatavilla."}',
    '2025-11-20T08:00:00Z', '2025-11-20T08:00:00Z', '2025-11-20T08:00:00Z');
